### ISSUE TITLE
How to disable colors and font weight

### ISSUE THREAD

**Issue by fbrundu** [platformio/platformio-atom-ide-terminal#188]
Hi,
Is there a way to disable colors and font weight?
I tried from the style sheet but the terminal uses inline spans, which may not be controlled by the former.

Thanks,
Francesco

**Comment by bretonics** [comment]
To add to this, specifically to the 'weight' comment... it looks to me like the text displayed is "antialias". Much like in the regular Terminal settings, switching the "Antialias text" results in a thiner text with the same font. Is this the default?

Can a switch be added?

**Comment by zfenj** [comment]
For lighter text open styles.less:

Edit > Stylesheet ...

And insert:

```
.platformio-ide-terminal .xterm {
  * { font-weight: lighter !important; }
}
```

**Comment by bretonics** [comment]
@zfenn know how to control the ANSI colors?

**Comment by francescoboc** [comment]
the solution proposed by @zfenn does nothing for me...

**Comment by the-j0k3r** [comment]
```css
.platformio-ide-terminal.terminal-view .xterm {
  * { font-weight: lighter !important; }
}
```
that works, if not

```css
.platformio-ide-terminal.terminal-view .xterm > .terminal {
  * { font-weight: lighter !important; }
}
```

Further reading https://www.w3schools.com/csSref/pr_font_weight.asp

both tested and working
