### ISSUE TITLE
Is there a way to change the cursor at the prompt?

### ISSUE THREAD

**Issue by uribe-convers** [platformio/platformio-atom-ide-terminal#226]
I'm wondering if there is a way to change the cursor to a vertical line (pipe) instead of the current block. Just as in the preferences in the terminal app in Mac, see below.

Thanks,
Simon 

![screen shot 2017-05-10 at 7 06 18 am](https://cloud.githubusercontent.com/assets/7415899/25897855/37c3cbf8-354f-11e7-8042-defdb89550a7.png)

**Comment by suryaavala** [comment]
I was just wondering the same thing. It would be so cool to be to able to change the cursor type.

**Comment by uribe-convers** [comment]
Does anybody know how to get a pipe instead of a block?

**Comment by chenjau** [comment]
add to your stylesheet:
```less
.platformio-ide-terminal {
  .cursor-blink {
    .terminal-cursor {
      -webkit-animation: none !important;
      background: red;
      width: 2px; // pipe width
    }
  }
}
```
remove -webkit-animation line if you want animation.
