### ISSUE TITLE
Font brightness adjustable?

### ISSUE THREAD

**Issue by ecodoc** [platformio/platformio-atom-ide-terminal#420]
Can the intensity/brightness of the font be adjusted? The text seems very bright to me to the point that I want to dim it. Is there a way to do that or choose the brightness level?

**Comment by the-j0k3r** [comment]
Yes add this to Atom stylesheet..

```css
.platformio-ide-terminal.terminal-view .xterm > .terminal {
    opacity: .5 !important;
}
```

The opacity value `.5` can be changed to taste.
https://www.w3schools.com/CSSref/css3_pr_opacity.asp
