### ISSUE TITLE
Close button next to open terminals

### ISSUE THREAD

**Issue by jokedurnez** [platformio/platformio-atom-ide-terminal#43]
My close button is - unlike the printscreens in the readme - right next to the buttons for open terminals.  It's too close. From time to time I close all my terminals by accident and that's extremely annoying.  Would be cool if this button is elsewhere or prompts a 'are you sure?'.

**Comment by zaaack** [comment]
Find a hack way to solving this, just add these CSS code into your stylesheet file (`~/.atom/styles.less`)

```css

.platformio-ide-terminal.status-bar .status-container {
    min-width: 300px;
    width: auto;
    height: auto;
    display: inline-block;
}
```
