### ISSUE TITLE
output is colored incorrectly for white background

### ISSUE THREAD

**Issue by mattfg** [platformio/platformio-atom-ide-terminal#626]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have disabled all packages other than core packages and atom-ide-terminal
- [x] I have not reset Atom to defaults prior to submitting report.

### Description

Running the following commands in Windows terminal produces this output:

![image](https://user-images.githubusercontent.com/9244059/48981956-c180a780-f0d3-11e8-9750-289d83010661.png)

Running the same commands in platformio produces a different output:

![image](https://user-images.githubusercontent.com/9244059/52451576-80772b80-2b37-11e9-93b7-f528e5bf6d34.png)

I've tried with many different color combinations, it only seems to be wrong when background color is white. Foreground white is fine, background any-other-color is fine, it's just background white.

    write-host "hello" -ForegroundColor black -BackgroundColor white
    write-host "hello" -ForegroundColor red -BackgroundColor white
    write-host "hello" -ForegroundColor black -BackgroundColor gray
    write-host "hello" -ForegroundColor white -BackgroundColor darkgray

One weird thing is that when background is white AND foreground is black, then both foreground AND background are wrong (foreground becomes white). For other colors, only the background=white is wrong. You can see that in the first command, it's not black-on-black it's white-on-black instead of white-on-red.

In case it makes a difference, my color settings are:

- Ansi Normal: 128
- Ansi Normal White: 192

- Ansi Z Bright: 255
- Ansi Z Bright Black: 128
- Ansi Z Bright Blue: 64,64,192

### Steps to reproduce

1. Open a platformio terminal (platformio-ide-terminal:toggle)
2. Run `powershell`
3. run: 
    write-host "hello" -ForegroundColor black -BackgroundColor white
    write-host "hello" -ForegroundColor red -BackgroundColor white
    write-host "hello" -ForegroundColor black -BackgroundColor gray
    write-host "hello" -ForegroundColor white -BackgroundColor darkgray

**Expected behavior:**
The first line of text is black on white. The second line of text is red on white.

**Actual behavior:**
The first line of text is white on black. The second line of text is red on black.

**Reproduces how often:**
100%

### Versions

```
> atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

> apm --version

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.7.0
git
visual studio
```
OS name and version: Windows 10 Pro 1803
Platformio-ide-terminal version: 2.9.0

### Additional Information

config.cson.platformio-ide-terminal:

```
  "platformio-ide-terminal":
    ansiColors:
      normal:
        blue: "#000080"
        cyan: "#008080"
        green: "#008000"
        magenta: "#800080"
        red: "#800000"
        white: "#808080"
        yellow: "#808000"
      zBright:
        brightBlack: "#404040"
        brightBlue: "#4040c0"
    core:
      mapTerminalsTo: "File"
      mapTerminalsToAutoOpen: true
      workingDirectory: "Active File"
    style:
      fontFamily: "Courier New"
      fontSize: "16"
    toggles:
      autoClose: true
      runInsertedText: false
```
