### ISSUE TITLE
Run python in platformio-atom-ide-terminal

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#70]
Is it possible to auto run current file in platformio just by opening terminal? I mean auto run command "python + current filename.py. Is it possible? I try to run python with input directly in atom. Script plugin doesn't work, I can't find any working solution. I am sorry for my bad english.

**Comment by ghost** [comment]
Hello.

I am looking  for the same solution as ghost is asking for. I hope to share my workaround. It is too late to help Ghost, but my notes might be helpful to someone. 

When only needing to run Python scripts (..and python.exe is 'rooted'), the "autoRunCommand" can be set to "Python". So when the terminal opens, "python.exe" is started. Passing the filename of the script is  the goal but seem to be difficult to do. (Maybe someone has an answer?)

The workaround uses the "customText" facility coupled with a custom keymap. The "customText" can hand over the filename of the script to be executed.

I have mapped the following keys with the functions:
ALT + ,     ----   activate the interactive Python shell and execute the script file
ALT + .     ----   restart / execute again the script where the Python shell is still active
ALT + /    ----   stop / exit the Python shell to return to the 'normal' terminal mode

(end part 1)

**Comment by ghost** [comment]
(part 2)
Now follow the files to change to give the before mentioned function:
```
### ...\.atom\config.cson

"*":
  editor:
  "platformio-ide-terminal":
    core:
      autoRunCommand: "python"  # When only use Python
      mapTerminalsTo: "File"
      shell: "C:\\Windows\\System32\\cmd.exe"  # <alternative>
      # <default> shell: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      workingDirectory: "Active File"
    customTexts:
      customText1: "python -i $D\\$F"  # New execution
      customText2: "exec(open(r'$D\\$F').read())"  # Restart
      customText3: "exit()" # Close Python session, return to terminal
```
```
### ...\.atom\keymap.cson  

'.platform-linux atom-workspace, .platform-win32 atom-workspace':
  'alt-,': 'platformio-ide-terminal:insert-custom-text-1'  # python -i FILE
  'alt-.': 'platformio-ide-terminal:insert-custom-text-2'  # exec(open(r'FILE').read())
  'alt-/': 'platformio-ide-terminal:insert-custom-text-3'  # exit()

'.platform-darwin .platformio-ide-terminal .terminal':
  'alt-,': 'platformio-ide-terminal:insert-custom-text-1'  # python -i FILE
  'alt-.': 'platformio-ide-terminal:insert-custom-text-2'  # exec(open(r'FILE').read())
  'alt-/': 'platformio-ide-terminal:insert-custom-text-3'  # exit()
```

As a bonus, add context menu items for the terminal:
```
### ...\.atom\packages\platformio-ide-terminal
###  \menus\platformio-ide-terminal.cson 
     
  '.platformio-ide-terminal .terminal': [
    {label: 'Copy', command: 'platformio-ide-terminal:copy'},
    {label: 'Paste', command: 'platformio-ide-terminal:paste'},
    {type: 'separator'},
    {label: 'Hide', command: 'platformio-ide-terminal:hide'},
    {label: 'Close', command: 'platformio-ide-terminal:close'},
    {type: 'separator'},
    {label: 'Start PY', command: 'platformio-ide-terminal:insert-custom-text-1'},
    {label: 'Restart PY', command: 'platformio-ide-terminal:insert-custom-text-2'},
    {label: 'Stop PY', command: 'platformio-ide-terminal:insert-custom-text-3'}
  ]
```

Comments and alternate ideas are welcome.
- Dan
