### ISSUE TITLE
[FR] scrollbar

### ISSUE THREAD

**Issue by farfromrefug** [platformio/platformio-atom-ide-terminal#9]
I really like your implementation and would like to use it with the atom-build package.
Now there is some little things i miss. One of them is the scrollbar.
When launching a build i might have a lot of lines!
Showing the scrollbar would be amazing!
##

**Comment by the-j0k3r** [comment]
Its probably related to https://github.com/platformio/platformio-atom-ide-terminal/blob/master/styles/platformio-ide-terminal.less#L76

However in Atom, Ive added 
```css
.platformio-ide-terminal.terminal-view .xterm > .terminal {
  overflow-y: visible !important;
}
``` and nothing has changed

**Comment by the-j0k3r** [comment]
Managed to get both scrollbars (only works like below and both y/x) showing but vertical (y) doesnt work, clearly scrolling buffer is not the same.
```css
.platformio-ide-terminal.terminal-view .xterm > .terminal {
  overflow: show !important;
}
```
